# Change these first
owner: haku-host # Your GitHub organization or username, where this repository lives
repo: side-monitor # The name of this repository

sites:
  - name: MSK1 HTTPS (Pterodactyl Xeon)
    url: https://msk1.haku.host
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404
  - name: MSK2 HTTPS (Pterodactyl Xeon)
    url: https://msk2.haku.host
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404
  - name: MSK3 HTTPS (Pterodactyl Ryzen)
    url: https://msk3.haku.host
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404
  - name: MSK4 HTTPS (Internal services)
    url: https://haku.host
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404
  - name: MSK5 (VDS Xeon)
    url: $MSK5
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404
  - name: Billing
    url: https://haku.host
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404
  - name: Pterodactyl
    url: https://my.haku.host
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404
  - name: HakuStack
    url: https://stack.haku.host
    expectedStatusCodes:
      - 200
      - 201
  - name: HakuPay Backend
    url: $HAKUPAY
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404
  - name: Graphana
    url: https://status.haku.host/public-dashboards/605083e175e849918ade2240b60db260
    expectedStatusCodes:
      - 200
      - 201
  - name: Uptime Kuma
    url: https://status.haku.host
    expectedStatusCodes:
      - 200
      - 201
  - name: Wiki
    url: https://wiki.haku.host
  - name: archlinux.gay
    url: https://archlinux.gay

status-website:
  theme: ocean
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: side.status.haku.host
  baseUrl: /side-monitor
  favicon: https://raw.githubusercontent.com/haku-host/side-monitor/refs/heads/master/haku.png
  logoUrl: https://raw.githubusercontent.com/haku-host/side-monitor/refs/heads/master/haku.svg
  name: Haku Host
  introTitle: "Внешнее наблюдение за аптаймом серверов."
  introMessage: Здесь можно посмотреть реальную доступность машин за последнее время
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
